version: '3.4'

services:
  imagegram:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DEV_PLATFORM=DOCKER
    ports:
      - '3003:3003'
    depends_on:
      - mongo
    networks:
      - app-tier

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: localhost
    volumes:
      - mongo_data:/data/db
    ports:
      - '27017:27017'
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge

volumes:
  app-node-modules:
    driver: local
  mongo_data:
    driver: local